### ISSUE TITLE
There's this weird window in the middle of the screen, how do I turn it off?

### ISSUE THREAD

**Issue by GreenNBlacko** [zeas2/Kirikiroid2#101]
![Screenshot_20200305-020039](https://user-images.githubusercontent.com/45263750/75904429-89dfde00-5e86-11ea-8bc8-75cce4678e88.png)
Been searching through the settings and didn't find any stuff about debug mode or something in that matter.. Is it just my phone or is anyone else experiencing it?

My phone is Sony xperia x f5121 android 8.0.0 rooted, just in case that helps figure it out.

**Comment by hak0** [comment]
I can confirm the same problem. My guess is that the xp3 file needs some modification. Did you copy them directly from the international version on steam?

**Comment by GreenNBlacko** [comment]
> I can confirm the same problem. My guess is that the xp3 file needs some modification. Did you copy them directly from the international version on steam?

Yes. 

So it should work just fine with other vns?

**Comment by GreenNBlacko** [comment]
> > I can confirm the same problem. My guess is that the xp3 file needs some modification. Did you copy them directly from the international version on steam?
> So it should work just fine with other vns?

Tested with nekopara, everything seems fine, which means that it's the game's files that are causing this.. Guess I'll have to wait for a patch.

**Comment by Mirai78** [comment]
We fixed the problem on lamunation.
![20200310_172829](https://user-images.githubusercontent.com/62011399/76298592-9c587e00-62b1-11ea-9d44-122cbff26d0e.png)

**Comment by Mirai78** [comment]
You need to join our Discord group
