### ISSUE TITLE
Launched app for first time, nothing shown.

### ISSUE THREAD

**Issue by blorgus1** [zeas2/Kirikiroid2#112]
As the title says I recently purchased and opened the app, and none of my files or folders are shown and I don't know what to do. I uninstalled and reinstalled, checked my folders, nothing I can do. Image attached. Thank you for your assistance.
![Screenshot_20201222-144233_Kirikiroid2](https://user-images.githubusercontent.com/76495550/102927574-3a928a80-4465-11eb-9533-b4b6aa7e98b6.jpg)

**Comment by Mirai78** [comment]
Can you check your permission manager maybe you denied access to storage

**Comment by blorgus1** [comment]
Solved the issue, moved my files to one of the given directories
