### ISSUE TITLE
Cannot find storage file:// ./data/app/org.tvp.kirikiri2_free-bw9vy_-1amq5mcldam1lqg==/base.apk

### ISSUE THREAD

**Issue by narb-btb** [zeas2/Kirikiroid2#26]
When i tap the file ends with .xp3, it goes "Cannot find storage file:// ./data/app/org.tvp.kirikiri2_free-bw9vy_-1amq5mcldam1lqg==/base.apk", how to solve this please?

**Comment by Demos25** [comment]
you need to buy v1.3.4

**Comment by zeas2** [comment]
Duplicate of #17
