### ISSUE TITLE
"License Fail" 1002 1

### ISSUE THREAD

**Issue by farson135** [zeas2/Kirikiroid2#30]
I recently purchased the app for my Galaxy S9, and every time I open the app I get the error in the title. I have tried power cycling my phone. I have tried reinstalling the app. I have tried uninstalling the app, clearing my google play cache, reinstalling the app, and power cycling. 

Edit: The problem has apparently fixed itself. I didn't do anything, so if anyone else has the same problem, just wait a few days.

**Comment by Demos25** [comment]
This was fixed in updated version on google play
