### ISSUE TITLE
iOS1.3.6无法存档(也许是部分游戏）

### ISSUE THREAD

**Issue by llorande** [zeas2/Kirikiroid2#39]
[在贴吧还是上面逛了一下准确来说应该不止草猫，部分游戏都有无法存档的现象]
试了试别的游戏，新放进去的游戏都有无法存档的问题，而原本放在里面都游戏则没有问题
图中游戏是nekopara vol.1,实际上测试过0，1，2都不能存档
![img_0927](https://user-images.githubusercontent.com/40350398/41521551-2c57106e-7305-11e8-9f45-992f712fb3de.PNG)

**Comment by llorande** [comment]
iOS版本是11.4

**Comment by zeas2** [comment]
duplicate of #34
