### ISSUE TITLE
安卓google play版1.3.6 无法存档

### ISSUE THREAD

**Issue by Ciayvhe** [zeas2/Kirikiroid2#40]
自从前几天google play版更新的1.3.6版后就开始无法存档了，和ios一样的问题，安卓系统是8.0

**Comment by Ciayvhe** [comment]
![kirikiroid2_2018-06-20-01-22-37](https://user-images.githubusercontent.com/40423240/41647259-bbe11434-742a-11e8-81d2-a112979d5bfd.jpg)

**Comment by zeas2** [comment]
duplicate of #34
