### ISSUE TITLE
「キュリオディーラー」没有立绘

### ISSUE THREAD

**Issue by Kuisijiang** [zeas2/Kirikiroid2#46]
游戏名称：キュリオディーラー
游戏厂商：AXL
发售日期：2018-06-29
Getchu介绍页：http://www.getchu.com/soft.phtml?id=1011427
原公司介绍页：http://www.axl-soft.jp/products/15
Kirikiroid2版本: 1.3.9
系统版本: Android 7.0
游戏cg和存读档正常，但所有角色的立绘都无法显示

**Comment by zeas2** [comment]
[补丁库](https://zeas2.github.io/Kirikiroid2_patch/patch/)已更新
