### ISSUE TITLE
1.3.9闪退

### ISSUE THREAD

**Issue by fungalplayer** [zeas2/Kirikiroid2#56]
华为安卓 8.0.0 EMUI 8.0.0
不知道是不是普遍问题

**Comment by woeijiunn88** [comment]
手机语言是否是中文界面？
如果是英文界面的话会闪退。（前版本遇过，不懂现在这个版本是不是有一样的问题

**Comment by fungalplayer** [comment]
原来如此，感谢！还请及时解决这个问题（虽然好像不太好解决啊）
