### ISSUE TITLE
Fata Morgana patch does not allow saving

### ISSUE THREAD

**Issue by AdjustMoni** [zeas2/Kirikiroid2#58]
When creating a save file you get the error:

Script exception raised
Member "AdjustMoni" does not exist

This is with the Mangagamer version.

**Comment by zeas2** [comment]
This issue is fixed, visit path list:
https://zeas2.github.io/Kirikiroid2_patch/patch

**Comment by AdjustMoni** [comment]
Thank you but it still runs into an error if you try to save or load. The screen turns all black and if you click Kirikiroid2's power/ quit button you get:

Script exception raised
The object is already invalidated

Screenshot: https://i.imgur.com/ut7IKY9.png

**Comment by zeas2** [comment]
Ouch, the patch update again...

**Comment by AdjustMoni** [comment]
Saving and loading works without a problem now, thank you!
