### ISSUE TITLE
Comyu patch often runs into errors

### ISSUE THREAD

**Issue by AdjustMoni** [zeas2/Kirikiroid2#60]
With the Comyu patch most instances of something happening like an attack will result in the error:

Script exception raised
Member "copyTexture" does not exist

I've managed to get past 2 of the errors by:

1st: Using the krz_xp3conv.exe tool. 

2: Changing the Advanced Renderer Option > Soft Renderer Option > Texture Compression option in Kirikiroid2 to Iz4+TLG5, then clicking on skip text when an error is about to happen.﻿

Edit: There is also this error that is impossible to pass in Initiation > The Hounds of Tindalos 02:  https://i.imgur.com/KpQTI2B.png

**Comment by zeas2** [comment]
Do you applied the patch ?
Maybe the English version uses different encrypt algorithm caused this issue.
So I changed patch2.xp3 to zip format, to avoid that.
Visit https://zeas2.github.io/Kirikiroid2_patch/patch
and search "コミュ" to get patch.

Notice that if you applied english patch to original jap game, do not simply override it.
You should change the file name of patch2.xp3 to patch3.xp3

**Comment by AdjustMoni** [comment]
I think I using an outdated patch, I have downloaded it again and it works without a problem in both Japanese and English. Thanks!
