### ISSUE TITLE
Crash On Android 8.1

### ISSUE THREAD

**Issue by mnixry** [zeas2/Kirikiroid2#84]
System: lineage OS 15.1(based on Android 8.1 AOSP)
LogCat:Failed to find layer(org.tvp.kirikiri2_ free _10304/org.tvp.kirikiri2_ free_ 10304.Kirikiroid2#0) inlayer parent (no-parent).

**Comment by BC63** [comment]
English system language？

**Comment by mnixry** [comment]
为什么该软件无法在非简体中文的系统下工作？

**Comment by BC63** [comment]
我也想知道...可能是作者没想到还有人用其他语言的系统吧

**Comment by Hatsuki5601** [comment]
一样希望能解决这个问题，为什么语言不是中文就会闪退

**Comment by TkzcM** [comment]
Google Play 上的付费版可以在所有语言下运行

**Comment by soloopooo** [comment]
小米9miui10.2稳定版android9.0英文版本刚刚点开就闪退，但是简体中文版却没有问题，希望修复
